### ISSUE TITLE
うっ・・・

### ISSUE THREAD

**Issue by ikuwow** [kanottyan/software_development_subject#1]
cloneしても必要なコードが足りない・・。

**Comment by kanottyan** [comment]
むむむ。。。！？

**Comment by kanottyan** [comment]
まだcloneできないですか？

**Comment by ikuwow** [comment]
cloneはできますが、webrootディレクトリがなかったりして動作させられなかったということでした。いまは動作させられました！

core.phpとdatabase.phpがそのまま共有されていて危ない！
layout.ctpを書き換えましょう。bootstrap3でお手軽にクールな感じのレイアウトができます。
TopsControllerを作るよりも、PagesControllerで作ったほうがよかったですね。cakephpはただの静的なページを作る場合はPagesControllerを使う、という風習があります。

**Comment by kanottyan** [comment]
いろいろありがとうございます！！まだ作成中なんです。時間の取得と表示が意外と難しい。。

・core.phpとdatabase.phpがそのまま共有されていて危ない！
→.gitignoreに追加なイメージですかね？

・layout.ctpを書き換えましょう。bootstrap3でお手軽にクールな感じのレイアウトができます。
→bootstrapがまったくわからないーー...。orz
時間あったら編集してみます！

・TopsControllerを作るよりも、PagesControllerで作ったほうがよかったですね。
→そうなんですね。ありがとうございます！

**Comment by kanottyan** [comment]
がぁぁ....。

1日中かけて結局、ユーザーごとの最後に出勤した時間と退勤した時間を取得するメソッドが作れず...。

どんな方針でやるといいんでしょうか...？？

**Comment by kanottyan** [comment]
あっすみません、すっごいソースコード汚いですが、取得出来ました。

**Comment by kanottyan** [comment]
が、キレイな方法があるなら教えて頂きたいです。。
